# Generated by Django 5.2 on 2025-05-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('funcionario', 'Funcionário')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
